apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: 2022mt93105dharrani/scalable_service_group_13:movie_service_V1.1
        ports:
        - containerPort: 8094
      imagePullSecrets:
      - name: my-registry-secret
