apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8094
      nodePort: 30000
    #  type: ClusterIP
  type: NodePort
    #nodePort: 8094
